### ISSUE TITLE
ریسورس پک

### ISSUE THREAD

**Issue by MDarvishi5124** [jd1378/Persian-Font-Fixer#1]
سلام، این فوق العاده‌ست!
بنظر نمیشه این رو توی قالب ریسورس پک نوشت، اما خواستم ازت سوال پرسیده باشم

**Comment by jd1378** [comment]
سلام
پروژه برای 7 8 سال پیشه، واقعا ایده ای ندارم که میشه یا نه الان
ولی حدس میزنم که نمیشه
بازم سرچ بزن، شاید یه چیزایی پیدا کردی

**Comment by jd1378** [comment]
@MDarvishi5124 

یه حرکتی برای تست میتونی بزنی
یه نگاه کوتاه انداختم به ریسورس پک، احتمال اینکه با استفاده از یک فونت ttf یا otf فارسی فیکس شه هست، 
https://minecraft.wiki/w/Resource_pack#Fonts

پیشنهاد میدم یه فونت فارسی معروف برای تست استفاده کنی ببینی درست میشه یا نه

**Comment by MDarvishi5124** [comment]
ماینکرفت تو سطوح خیلی پایین تری از فونت ttf استفاده می‌کنه و ویژگی های فونت، ویژگی های متن رو تغییر نمی‌ده.
قبلاً تست کردم، و دیگران هم تست کردن. الان ماینکرفتم دچار مشکل شده، ولی دوباره تستش می‌کنم.

**Comment by jd1378** [comment]
جالب اینجاست تو این  7 8 سال هنوز درستش نکردن 😂
و جالب تر این بود که زبان بازی رو میذاشتی رو فارسی درست میشد (هر چند که داغونه در کل)

**Comment by MDarvishi5124** [comment]
ماینکرفت جاوا(پیسی) رو کلاً ول کردن به امون خدا، ماینکرفت pe(موبایل) رو هم اصلاً اینها رو بهش اضافه نکردن. از زمانی که ماینکرفت به مایکروسافت فروخته شد، افتضاح شد.
برای زبان فارسی جدا از نمایش بدش، ترجمه هاش هم مشکل داره. با اینکه ترجمه ها رو مردم تو crowdin ثبت می‌کنن و الان ترجمۀ ماینکرفت 99 درصده، ولی ماینکرفت نصفش رو به بازی اضافه کرده.

**Comment by jd1378** [comment]
چند روز پیش برای یک بنده خدایی ماینکرفت خریدم
تازه بعد چندین سال فهمیدم تحریمم شدیم توسط مایکروسافت و فقط با قند شکن میشه رو سرورای پریمیوم بازی کرد
ناراحت کنندست واقعا
قدیما از این مسخره بازیا نبود

**Comment by MDarvishi5124** [comment]
![2024-09-16_13 08 43](https://github.com/user-attachments/assets/3e67d384-e5c8-4dc3-a305-629b289bcbf5)
اسکرین شات
[Arad.zip](https://github.com/user-attachments/files/17010914/Arad.zip)
ریسورس‌پکی که استفاده شده بود(از فونت وزیرمتن استفاده کردم)

توی این اسکرین شات، نه تنها انتظارات ما، بلکه خود فونت هم درست نمایش داده نمیشه. تو همرفتن حروف، یا فاصله های زیاد غیر معمول، نشون می‌ده ماینکرفت سیستم درستی طراحی نکرده.

**Comment by jd1378** [comment]
پس متاسفانه بهترین حالت همون mod برای کلاینت هست
 که امکان فراگیر شدن فیکس رو کم میکنه
یا پلاگین سمت سرور

پلاگین منم خیلی قدیمیه، احتمالا یه باز نویسی بشه بهتر بشه کردش

**Comment by MDarvishi5124** [comment]
حله داداش. دمت گرم کمک کردی

حیف از سمت ما، کار خاصی قابل انجام نیست
